export const SUBJECT_ACTIONS = {
  FETCH_START: "SUBJECT_FETCH_START",
  FETCH_SUCCESS: "SUBJECT_FETCH_SUCCESS",
  FETCH_FAILURE: "SUBJECT_FETCH_FAILURE",
  ADD_SUBJECT: "SUBJECT_ADD",
  UPDATE_SUBJECT: "SUBJECT_UPDATE",
  DELETE_SUBJECT: "SUBJECT_DELETE",
};