export const TASK_ACTIONS = {
  FETCH_START: "TASK_FETCH_START",
  FETCH_SUCCESS: "TASK_FETCH_SUCCESS",
  FETCH_FAILURE: "TASK_FETCH_FAILURE",
  ADD_TASK: "TASK_ADD",
  UPDATE_TASK: "TASK_UPDATE",
  DELETE_TASK: "TASK_DELETE",
};